### ISSUE TITLE
link from Capstone binding list

### ISSUE THREAD

**Issue by aquynh** [x1nixmzeng/cs_x86#4]
hi,

this looks very cool! do you want to make a pull request to add your binding to the list at 
https://github.com/aquynh/capstone/blob/master/bindings/README?

keep it up, cheers!

**Comment by x1nixmzeng** [comment]
Thanks for the comment! 

Reading through this thread https://github.com/aquynh/capstone/issues/1315 there is a far better (more complete) library here: https://github.com/9ee1/Capstone.NET
