### ISSUE TITLE
Update Capstone Submodule

### ISSUE THREAD

**Issue by RadWolfie** [x1nixmzeng/cs_x86#6]
Hi @x1nixmzeng, we need capstone submodule update to latest branch, aka commit https://github.com/aquynh/capstone/commit/d71c95b09b1fa478c0ab9294b07fd6f2efaa1b31. Reason for this is to able use CMake's install method. At this time, we're not able to use install method because of cstool's broken install method using `CMAKE_BINARY_DIR` instead of `CMAKE_CURRENT_BINARY_DIR`. It would be great to verify if it works as intended or make necessary changes to work with capstone.

P.S. I'm not able to verify it since I am not an expert with C# area nor with capstone.

**Comment by RadWolfie** [comment]
Actually, capstone.pc is enforced into `CMAKE_BINARY_DIR`. I'm not sure how accurate this is being correct. It will still work for the install method anyway.

**Comment by x1nixmzeng** [comment]
Thanks for opening the issue, I will investigate what is needed to update it

**Comment by RadWolfie** [comment]
Any update with this task?

**Comment by x1nixmzeng** [comment]
I've pushed the branch `support-cmake-install` which updates capstone and removes the msvc project.

The capstone install project may need turning off as it probably ships with headers
